# Generated by Django 5.2.6 on 2025-09-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
