# Generated by Django 5.2.6 on 2025-09-09 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vote_type",
                    models.CharField(
                        choices=[
                            ("character", "Character"),
                            ("film", "Film"),
                            ("starship", "Starship"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("item_id", models.PositiveIntegerField()),
                (
                    "votes",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["vote_type", "votes"],
                        name="voting_vote_vote_ty_8890c1_idx",
                    )
                ],
                "unique_together": {("vote_type", "item_id")},
            },
        ),
    ]
